### ISSUE TITLE
Issue when importing products.

### ISSUE THREAD

**Issue by sambrown03** [hkadm/HostkeyResellerMod#7]
Oops!
Something went wrong and we couldn't process your request.
Please go back to the previous page and try again.

For additional assistance, please reference the [WHMCS TroubleShooting Guide »](https://docs.whmcs.com/Troubleshooting_Guide)

TypeError: Cannot access offset of type string on string in /home/leveluphostingco/public_html/modules/addons/hostkeyresellermod/lib/HostkeyResellerModLib.php:787
Stack trace:
#0 /home/leveluphostingco/public_html/modules/addons/hostkeyresellermod/lib/HostkeyResellerModLib.php(274): WHMCS\Module\Addon\Hostkeyresellermod\HostkeyResellerModLib::clearProductConfigOptions(Array, 'OS ', 'OS')
#1 /home/leveluphostingco/public_html/modules/addons/hostkeyresellermod/hostkeyresellermod.php(168): WHMCS\Module\Addon\Hostkeyresellermod\HostkeyResellerModLib::loadPresetsIntoDb(Array, Array, Array, Array, '1')
#2 /home/leveluphostingco/public_html/lvlupadmin/addonmodules.php(0): hostkeyresellermod_output(Array)
#3 {main}

**Comment by acround** [comment]
Ok, I have just fixed the problem. Please, download new version and try again.

**Comment by sambrown03** [comment]
DivisionByZeroError: Division by zero in /home/leveluphostingco/public_html/modules/addons/hostkeyresellermod/lib/HostkeyResellerModLib.php:1021
Stack trace:
#0 /home/leveluphostingco/public_html/modules/addons/hostkeyresellermod/lib/HostkeyResellerModLib.php(888): WHMCS\Module\Addon\Hostkeyresellermod\HostkeyResellerModLib::addPricing('bm', 557, Array)
#1 /home/leveluphostingco/public_html/modules/addons/hostkeyresellermod/lib/HostkeyResellerModLib.php(306): WHMCS\Module\Addon\Hostkeyresellermod\HostkeyResellerModLib::addOsProductConfigOptionsSub(Array, 218)
#2 /home/leveluphostingco/public_html/modules/addons/hostkeyresellermod/hostkeyresellermod.php(170): WHMCS\Module\Addon\Hostkeyresellermod\HostkeyResellerModLib::loadPresetsIntoDb(Array, Array, Array, Array, '1')
#3 /home/leveluphostingco/public_html/lvlupadmin/addonmodules.php(0): hostkeyresellermod_output(Array)
#4 {main}

**Comment by acround** [comment]
Apparently, you don't have a default currency (EUR or RUB). It depends on which invapi you get presets from (.com or .ru).
I added code to detect this situation, so I suggest adding the appropriate currency to the billing with the right rate relative to your default currency, download the latest version of the module and try again.

**Comment by sambrown03** [comment]
I am using GBP so neither, Is that why?

**Comment by acround** [comment]
OK, but we use EUR for our clients. So, please, make a record with euro in your billing with the rate relative to GBR, and all will be ok.
